server:
  port: 12300

spring:
  profiles:
    active: dev
  application:
    name: fulfillment-cp

log:
  path: /data/logs/app
  level: info

logging:
  config: classpath:logback.xml
  path: ${log.path}
  level:
    com.mallcai.fulfillment.dc.dao: debug
